
-- Table for 4-digit connection codes generated by parents
CREATE TABLE public.connection_codes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  parent_id uuid NOT NULL,
  code text NOT NULL,
  is_used boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL DEFAULT (now() + interval '24 hours')
);

-- Table for caregiver-parent connections
CREATE TABLE public.caregiver_connections (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  caregiver_id uuid NOT NULL,
  parent_id uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(caregiver_id, parent_id)
);

-- RLS for connection_codes
ALTER TABLE public.connection_codes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Parents can insert their own codes"
ON public.connection_codes FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = parent_id);

CREATE POLICY "Parents can view their own codes"
ON public.connection_codes FOR SELECT
TO authenticated
USING (auth.uid() = parent_id);

CREATE POLICY "Caregivers can view codes to validate"
ON public.connection_codes FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Caregivers can update codes to mark used"
ON public.connection_codes FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);

-- RLS for caregiver_connections
ALTER TABLE public.caregiver_connections ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Caregivers can insert connections"
ON public.caregiver_connections FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = caregiver_id);

CREATE POLICY "Caregivers can view their connections"
ON public.caregiver_connections FOR SELECT
TO authenticated
USING (auth.uid() = caregiver_id);

CREATE POLICY "Parents can view connections to them"
ON public.caregiver_connections FOR SELECT
TO authenticated
USING (auth.uid() = parent_id);

-- Allow caregivers to view connected parent profiles
CREATE POLICY "Caregivers can view connected parent profiles"
ON public.profiles FOR SELECT
TO authenticated
USING (
  user_id IN (
    SELECT parent_id FROM public.caregiver_connections WHERE caregiver_id = auth.uid()
  )
  OR auth.uid() = user_id
);
